package MathBaseball.math_bb2;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;


/**
 * Created by Febo on 2/3/14.
 */
public class Baseball extends JPanel implements ActionListener, KeyListener {
    private JCheckBox checkBox1;
    private JButton registerButton;
    private JTextPane toLoginEnterYourTextPane;
    private JPasswordField passwordPasswordField;
    private JFormattedTextField usernameFormattedTextField;
    private JButton loginButton;
    private JPanel panel1;
    private Main frame;

    public Baseball() {
        $$$setupUI$$$();

        loginButton.addActionListener(this);
        checkBox1.addActionListener(this);
        registerButton.addActionListener(this);
        passwordPasswordField.addKeyListener(this);
        usernameFormattedTextField.addKeyListener(this);


    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();

        if (source == loginButton) {
            //If for username and password
            if (checkBox1.isSelected()) {
                logInTeacher(usernameFormattedTextField.getText(), passwordPasswordField.getPassword());
            } else {
                logInStudent(usernameFormattedTextField.getText(), passwordPasswordField.getPassword());
                MainMenu mm = new MainMenu();
                frame = new Main(mm.$$$getRootComponent$$$());
            }
        } else if (source == registerButton) {
            Register r = new Register();
            frame = new Main(r.$$$getRootComponent$$$());
        }
    }

    public void keyTyped(KeyEvent e) {

    }


    public void keyPressed(KeyEvent e) {

    }


    public void keyReleased(KeyEvent e) {

    }

    public void registerTeacher() {

    }

    public void logInStudent(String u, char[] p) {

    }

    public void logInTeacher(String u, char[] p) {

    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-10053121));
        panel1.setFont(new Font("Freestyle Script", panel1.getFont().getStyle(), panel1.getFont().getSize()));
        checkBox1 = new JCheckBox();
        checkBox1.setText("Teacher");
        panel1.add(checkBox1, new GridConstraints(2, 0, 2, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        registerButton = new JButton();
        registerButton.setText("Register New User");
        panel1.add(registerButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        toLoginEnterYourTextPane = new JTextPane();
        toLoginEnterYourTextPane.setEditable(false);
        toLoginEnterYourTextPane.setFont(new Font("HGSMinchoL", toLoginEnterYourTextPane.getFont().getStyle(), 24));
        toLoginEnterYourTextPane.setText("To login enter your teacher provided username and password. If you are a teacher check the box below before clicking login.");
        panel1.add(toLoginEnterYourTextPane, new GridConstraints(0, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        passwordPasswordField = new JPasswordField();
        passwordPasswordField.setText("Password");
        passwordPasswordField.setToolTipText("");
        panel1.add(passwordPasswordField, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        usernameFormattedTextField = new JFormattedTextField();
        usernameFormattedTextField.setText("Username");
        panel1.add(usernameFormattedTextField, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        loginButton.setMnemonic('L');
        loginButton.setDisplayedMnemonicIndex(0);
        panel1.add(loginButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
