package MathBaseball.math_bb2;



import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 * Created by Febo on 2/9/14.
 */
public class MainMenu extends JPanel implements MouseListener {
    private JPanel panel1;
    private JButton viewStatsButton;
    private JButton manageTeamButton;
    private JLabel playBallLabel;
    private Main frame;

    public MainMenu() {
        playBallLabel.addMouseListener(this);
        playBallLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }


    public void mouseClicked(MouseEvent e) {
        Object source = e.getSource();

        if (source == playBallLabel) {
            PlayBall play = new PlayBall();
            frame = new Main(play.$$$getRootComponent$$$());
        }
    }


    public void mousePressed(MouseEvent e) {

    }


    public void mouseReleased(MouseEvent e) {

    }


    public void mouseEntered(MouseEvent e) {

    }


    public void mouseExited(MouseEvent e) {

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 3, new Insets(25, 25, 25, 25), -1, -1));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), null));
        viewStatsButton = new JButton();
        viewStatsButton.setEnabled(true);
        viewStatsButton.setText("View Scores");
        panel1.add(viewStatsButton, new GridConstraints(0, 2, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageTeamButton = new JButton();
        manageTeamButton.setEnabled(true);
        manageTeamButton.setText("Manage Team");
        panel1.add(manageTeamButton, new GridConstraints(0, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        playBallLabel = new JLabel();
        playBallLabel.setFocusable(true);
        playBallLabel.setIcon(new ImageIcon(getClass().getResource("./playBallButton.png")));
        playBallLabel.setOpaque(false);
        playBallLabel.setText("");
        playBallLabel.setVisible(true);
        panel1.add(playBallLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
